### ISSUE TITLE
No gt.txt found on train

### ISSUE THREAD

**Issue by frederick0291** [buliasz/tesstrain-windows-gui#5] opened 2022-04-05 14:33 UTC
I am trying the gui out, I was able to pass through the issue where it was having problems with symbols that are not available for utf-8,  but after it made the boxes and lstmf files it gave me an error that there are "not enough gt.txt files found. Found 0" the ground truth files are in the same folder as the tif and box files so I am not sure why it wasn't able to detect the gt files.

I am also having issues with double quote marks causing an issue on the training box creation since latin-1 does not include smart quotes. Should I change the smart quotes in my gt files into straight quotes?

**Comment by frederick0291** [comment] 2022-04-12 13:09
Okay I was able to figure out the issue, if you have a folder path that has a space like `c://foo/bar buzz/`  the tool will have an error since it runs the commands in CLI and it doesn't surround the path to the .gt.txt files with quote marks. 

Workaround:
Move to a folder with no space in the path.

Fix:
Add quote marks to the ground truth path argument on CLI call.

**Comment by buliasz** [comment] 2022-04-13 04:16
Are you sure you have latest version? I've just tested using folder with spaces and everything is working properly.
There was a fix about month ago which fixed similar issues.

**Comment by frederick0291** [comment] 2022-04-13 06:18
![image](https://user-images.githubusercontent.com/40852439/163112191-92c40d85-3632-4f9a-8ff6-5803b524c365.png)

It's the third arg on the .box and .lstmf generation step that doesn't have the quote marks around the output dir.

**Comment by buliasz** [comment] 2022-04-13 14:33
Thank you for the picture, now i can see it. You've mislead me with your comment "it doesn't surround the path to the .gt.txt files with quote marks.". It was not .gt.txt or .box, it was actually during generation of the .lstmf file.
I didn't have this error on my test, because .lstmf files are not created if they are up to date, I needed to clean them (there's an option in Advanced tab for it), and I could reproduce the issue.
Anyways it is fixed now, thanks for the report!

**Closed** 2022-04-14 02:56 UTC
