### ISSUE TITLE
The preview function shows mojibake in gui, maybe wrong encoding? Where to edit the source code for preview? steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [buliasz/tesstrain-windows-gui#13] opened 2022-06-16 23:35 UTC
The preview function shows mojibake in gui, maybe wrong encoding? Where to edit the source code for preview? steve8000818@gmail.com

![image](https://user-images.githubusercontent.com/41010669/174195199-f295db3f-2fa0-4756-bbc5-a16003e345dc.png)

**Comment by buliasz** [comment] 2022-06-16 23:55
Preview code is in the `_recognition_preview.ahki` file. But I think the function that probably needs to be fixed is `OcrImageFile` which is in the `_helper.ahki` file. This one leads to the `ExecuteCommand` function from the `_console.ahki`.
I guess the issue is that StdOut from cmd.exe is in your local windows code page.

**Comment by buliasz** [comment] 2022-06-16 23:57
You can try fixing it by yourself or you can send me some example Ground Truth data and I'll do it when I find some time for it.

**Comment by buliasz** [comment] 2022-06-17 00:03
Look 2 messages above your question. Already answered.

**Comment by nissansz** [comment] 2022-06-17 00:09
[100split.zip](https://github.com/buliasz/tesstrain-windows-gui/files/8923496/100split.zip)
Check this sample ground truth data

**Comment by nissansz** [comment] 2022-06-17 00:35
[jp100.zip](https://github.com/buliasz/tesstrain-windows-gui/files/8923562/jp100.zip)
check trainneddata here

**Comment by nissansz** [comment] 2022-06-17 00:45
I tried to update with your source code, it does not work. Same wrong display result.

**Comment by buliasz** [comment] 2022-06-17 01:56
I've fixed it. Please try the new version.

**Comment by nissansz** [comment] 2022-06-17 02:12
Thank you.
But there is error when I tried to preview.
![image](https://user-images.githubusercontent.com/41010669/174210282-28f07eec-5f1a-4f9b-a76b-5da22e4d7ef8.png)

**Comment by buliasz** [comment] 2022-06-17 02:15
I don't understand Japanese, what does the exception message say?

**Comment by nissansz** [comment] 2022-06-17 02:16
The system cannot find the specified file.

**Comment by nissansz** [comment] 2022-06-17 02:17
which file did you updated? Maybe I can copy your new updated file to old version to make it work.

**Comment by buliasz** [comment] 2022-06-17 02:23
Fixed, check it now

**Comment by nissansz** [comment] 2022-06-17 02:35
thank you.
Will check later.
Also, for training datasets, can I put them in several sub folders for each font?
Did it support sub folders?

**Comment by buliasz** [comment] 2022-06-17 02:42
I don't think so. At the moment it executes commands the same way console training script does (from the main tesstrain repo). 
In the "Disscusions" section there's an "Ideas" category. You can use it to propose that. Maybe some day I'll have time to implement it or you or someone else will try doing it.
You can use just naming convention if the only think you want to achieve is have the input data ordered.

**Comment by buliasz** [comment] 2022-06-17 02:44
You can use separate folders for different Ground Truth input and to train different .traineddata targets, if that's your point.

**Comment by nissansz** [comment] 2022-06-17 02:51
I mean training for all fonts in a parent folder.
In paddle ocr, it supports reading label file with path for each image

**Comment by nissansz** [comment] 2022-06-17 02:51
I mean training for all fonts in a parent folder.
In paddle ocr, it supports reading label file with path for each image

**Comment by nissansz** [comment] 2022-06-17 03:10
![image](https://user-images.githubusercontent.com/41010669/174217257-3ca37f00-94e5-4907-ac72-69ca572a0cf7.png)

It can be displayed, but there is one problem.
The blank area is wrongly recognized as English letters.

**Comment by buliasz** [comment] 2022-06-17 03:20
I think this is just a matter of more training.

**Comment by nissansz** [comment] 2022-06-17 03:22
Ok. It can be solved by opencv cropping, but don't know how to execute in your source code.

**Comment by buliasz** [comment] 2022-06-18 14:51
I assume the issue from subject is now fixed.

**Closed by buliasz** 2022-06-18 14:51 UTC
